[package]
name = "chewing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The Chewing (酷音) intelligent Zhuyin input method."
documentation = "https://docs.rs/chewing"
license.workspace = true

include = [
  "AUTHORS",
  "COPYING",
  "Cargo.toml",
  "NEWS",
  "src/**/*.asn1",
  "src/**/*.rs",
  "src/editor/data/*",
]

[package.metadata.docs.rs]
features = ["sqlite"]

[workspace]
resolver = "3"
members = ["capi", "fuzzer", "tests/testhelper", "tools"]

[workspace.package]
version = "0.13.0-alpha.2"
edition = "2024"
rust-version = "1.88.0"
license = "LGPL-2.1-or-later"

[workspace.dependencies]
chewing = { path = ".", version = "0.13.0-alpha.2" }
chewing_capi = { path = "./capi", version = "0.13.0-alpha.2" }
env_logger = "0.11.0"
log = "0.4.0"
tempfile = "3.10.1"

[dependencies]
der = { version = "0.7.7", features = ["std"] }
log = { workspace = true }
rusqlite = { version = ">= 0.28.0", optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = []
sqlite = ["dep:rusqlite"]
sqlite-bundled = ["rusqlite/bundled", "sqlite"]

[profile.release]
opt-level = 3
debug = true
lto = true
panic = "abort"
codegen-units = 1
